### ISSUE TITLE
Move thread and RAM configuration out of Config and into Snakemake profiles.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#221]
### Problem Description

At the moment the threads and RAM resource available to Snakemake are currently stored in `config.yaml`.

```yaml
# Config file for rotary

## Directory for database installation
db_dir: "/Data/databases/rotary"

## Resources
threads: 20
# Memory in Gigabytes
#   At least ~55-60 GB is needed
memory: 100
```

However this causes an issue where if the config is transferred between computers (different states of cloud VMs or different computers across team members) and the user forgets to update the config file then the new computer will use the wrong number of threads. There is also potentially an issue where if you change the number of threads then Snakemake may attempt to rerun the workflow from scratch because the config file has been modified.

### Problem Solution

Snakemake has a feature called workflow profiles that are predefined configurations that specify how a workflow should be executed in different environments, such as local machines, HPC clusters, or cloud platforms. These profiles encapsulate settings like resource allocation, cluster submission commands, and execution parameters. By using profiles, users can easily switch between environments without altering the core workflow, ensuring consistent and reproducible execution. 

More details can be found here: https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles

For example:

```yaml
cores: 10
resources:
  mem_mb: 16000
cluster: "sbatch -A myaccount --mem={resources.mem_mb} --cpus-per-task={threads}"
jobscript: "/path/to/jobscript.sh"
conda-frontend: "mamba"
```

In these profiles you can also set up rule specific resources

```yaml
default-resources:
    mem_mb: 200
set-threads:
    myrule: 5
set-resources:
    myrule:
        mem: 500MB
```

By moving the threads and RAM resources to a profile we could allow the user to modify these values without modifying the config file. I propose we explore this option.
